apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  google-api-key: {{ .Values.google.apiKey | b64enc }}